---
title: "stl_lead_inequity"
format: html
editor: visual
---

## Data import and exploration

```{r}
library(tidyverse)
library(janitor)
```

### Read data

```{r}
# read in data
stl_lead <- read.csv(here::here("data", "stl_blood_lead.csv"))

# clean data
stl_lead <- stl_lead %>% clean_names()

# Get data summary
skimr::skim(stl_lead)
dim(stl_lead)
names(stl_lead)

ggplot(data = stl_lead, 
       aes(x = poverty_tot / total_pop, y = pct_elevated)) +
  geom_point() +
  theme_minimal() +
  labs(title = "Percent Poverty vs Percent Elevated", x = "Percent Population in Poverty", y = "Percent Elevated") +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}

#stl_lead_prop <- stl_lead %>% dplyr::mutate(prop_white = white / total_pop)

stl_lead_prop <- stl_lead

stl_lead_prop$prop_white <- (stl_lead_prop$white / stl_lead_prop$total_pop) 

stl_lead_prop
```

### Visualize Data

```{r}

stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = white * 100.0 / total_pop, color = poverty_tot * 100 / total_pop)) +
  geom_point() +
  theme_minimal() +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) + 
  labs(title = "Children with elevated blood levels (%) \n vs White Identifying (%)", 
       x = "Percentage of children with \n elevated blood lead levels", 
       y = "Percent identifying as white", 
       color = "Percentage of impoverished individuals (%)") +
  scale_color_gradient(low = "lightgreen", high = "darkgreen") +
  geom_smooth(method = "lm", se = FALSE, color = "red")


stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```

It seems like in areas with a higher percentage of white identifying individuals, the percentage of children with elevated blood lead levels is lower.

```{r}
pct_elevated_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) + 
  geom_histogram()

pct_elevated_plot

ggsave(here::here("figs", "pct_elevated_plot.png"), height = 6, width = 5)
```
